name: epistasis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- python>=3.6
- pandas
- numpy
- numba
- treeswift
- dendropy
- tqdm
- nextclade
- scipy
- networkx
- scikit-learn
- matplotlib
- seaborn
- jupyterlab
- nbconvert
- pip
- pip:
    - pyfish
