name: epistasis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- "python>=3.6,<3.11"
- pandas
- numpy
- numba
- treeswift
- dendropy
- tqdm
- nextclade
- scipy
- networkx
- scikit-learn
- matplotlib
- seaborn
- jupyterlab
- nbconvert
- openpyxl
- biopython
- pip
- pip:
    - pyfish
