name: epistasis-invitro
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
- "python>=3.6,<3.11"
- pandas
- numpy<1.20
- numba
- treeswift
- dendropy
- tqdm
- nextclade
- scipy
- networkx
- "scikit-learn>=0.20.0,<1"
- matplotlib
- seaborn
- jupyterlab
- nbconvert
- openpyxl
- biopython
- pip
- pip:
    - pyfish
    - epistasis
    - corner
